name: Lints

on: [push]

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: |
          cd contracts
          yarn
      - name: Update Modules
        run: |
          cd contracts
          yarn sync
      - name: Run lints
        run: |
          cd contracts
          yarn lint
